name: kinet_composer
description: A native pixel mapping and video composition tool.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.0
  
  # UI
  cupertino_icons: ^1.0.2
  window_manager: ^0.5.1 # For desktop window control
  bitsdojo_window: ^0.1.6 # Custom Window Title Bar
  
  # Logic
  path_provider: ^2.0.0
  file_picker: ^10.3.7
  shared_preferences: ^2.2.0
  
  # Networking
  http: ^1.1.0
  network_info_plus: ^7.0.0 # To get local IP
  
  # Video (Using media_kit for desktop support)
  media_kit: ^1.1.10
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.5
  archive: ^4.0.7
  flutter_colorpicker: ^1.1.0
  sunrise_sunset_calc: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
